### ISSUE TITLE
current `__builtin_clzll()` usage could lead to undefined behavior

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/bls12-381#7]
Originally reported here,
https://github.com/AntelopeIO/bls12-381/pull/6#issuecomment-1662387001
and there is some additional commentary on that PR on potential fixes. `__builtin_clzll()` is undefined when input is 0, which it may be here
https://github.com/AntelopeIO/bls12-381/blob/82a137ecdc010563a78673ddabf014dd0ec6ae77/src/scalar.cpp#L250-L251

**Comment by yarkinwho** [comment]
do you want me to fix that in the PR #6  together? It contains tons of optimization now anyway...

**Comment by spoonincode** [comment]
either way seems fine

**Comment by greg7mdp** [comment]
> do you want me to fix that in the PR #6 together? It contains tons of optimization now anyway...

works for me.
